name: PDFium-Build

on:
  push:
    branches:
      - cheftin
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macOS-latest
          # - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build on ${{ matrix.os }}
        env:
          CXAN_TOKEN_KDR2: ${{ secrets.CXAN_TOKEN_KDR2 }}
          NOTIFICATION_MM_WEBHOOK: ${{ secrets.NOTIFICATION_MM_WEBHOOK }}
        run: ./ci-build/build.sh
